name: API Tests (Bookstore + Allure + Pages)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest

    # Configure defaults/fallbacks here. If you set repo secrets EMAIL/PASSWORD,
    # they will override these at runtime via the bash fallbacks below.
    env:
      BASE_URL: http://127.0.0.1:8000
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      # ---------- Checkout ----------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- Java & Maven ----------
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # ---------- Python & FastAPI server ----------
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: server/requirements.txt

      - name: Install server dependencies
        working-directory: server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI in background
        working-directory: server
